version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "3307:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile-tomcat
    ports:
      - "8080:8080"
    depends_on:
      - db